# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-04 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='\u6635\u79f0')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='\u540d\u5b57')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='\u59d3\u6c0f')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('is_staff', models.BooleanField(default=False, help_text=b'\xe6\x98\xaf\xe5\x90\xa6\xe8\x83\xbd\xe5\xa4\x9f\xe7\x99\xbb\xe5\xbd\x95\xe7\xae\xa1\xe7\x90\x86\xe5\x90\x8e\xe5\x8f\xb0', verbose_name='\u804c\u5458\u72b6\u6001')),
                ('is_active', models.BooleanField(default=True, help_text=b'\xe7\x94\xa8\xe6\x88\xb7\xe6\x98\xaf\xe5\x90\xa6\xe8\xa2\xab\xe6\xbf\x80\xe6\xb4\xbb\xef\xbc\x8c\xe6\x9c\xaa\xe6\xbf\x80\xe6\xb4\xbb\xe5\x88\x99\xe4\xb8\x8d\xe8\x83\xbd\xe4\xbd\xbf\xe7\x94\xa8', verbose_name='\u662f\u5426\u6fc0\u6d3b')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('avatar_url', models.ImageField(blank=True, default=b'avatar/default_big.png', max_length=200, null=True, upload_to=b'avatar/%Y/%m', verbose_name='\u5934\u50cf220x220')),
                ('avatar_middle_thumbnall', models.ImageField(blank=True, default=b'avatar/default_middle.png', max_length=200, null=True, upload_to=b'avatar/%Y/%m', verbose_name='\u5934\u50cf104x104')),
                ('avatar_small_thumbnall', models.ImageField(blank=True, default=b'avatar/default_small.png', max_length=200, null=True, upload_to=b'avatar/%Y/%m', verbose_name='\u5934\u50cf70x70')),
                ('avatar_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5934\u50cfALT\u8bf4\u660e')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ\u53f7\u7801')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('valid_email', models.SmallIntegerField(choices=[(0, '\u5426'), (1, '\u662f')], default=0, verbose_name='\u662f\u5426\u9a8c\u8bc1\u90ae\u7bb1')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u516c\u53f8\u540d')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u804c\u4f4d\u540d')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u4e2a\u4eba\u4ecb\u7ecd')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u57ce\u5e02')),
                ('province', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7701\u4efd')),
                ('index', models.IntegerField(default=999, verbose_name='\u6392\u5217\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'db_table': 'user_profile',
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u5e7f\u544a\u6807\u9898')),
                ('description', models.CharField(max_length=200, verbose_name='\u5e7f\u544a\u63cf\u8ff0')),
                ('image_url', models.ImageField(upload_to=b'ad/%Y/%m', verbose_name='\u56fe\u7247\u8def\u5f84')),
                ('callback_url', models.URLField(blank=True, null=True, verbose_name='\u56de\u8c03url')),
                ('index', models.IntegerField(default=999, verbose_name='\u6392\u5217\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
            ],
            options={
                'ordering': ['index', 'id'],
                'db_table': 'ad',
                'verbose_name': '\u7f51\u7ad9\u5e7f\u544a',
                'verbose_name_plural': '\u7f51\u7ad9\u5e7f\u544a',
            },
        ),
        migrations.CreateModel(
            name='CareerCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u804c\u4e1a\u8bfe\u7a0b\u540d\u79f0')),
                ('short_name', models.CharField(max_length=10, unique=True, verbose_name='\u804c\u4e1a\u8bfe\u7a0b\u82f1\u6587\u540d\u79f0\u7b80\u5199')),
                ('image', models.ImageField(upload_to=b'course/%Y/%m', verbose_name='\u8bfe\u7a0b\u5c0f\u56fe\u6807')),
                ('description', models.TextField(verbose_name='\u6587\u5b57\u4ecb\u7ecd')),
                ('student_count', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('market_page_url', models.URLField(blank=True, null=True, verbose_name='\u8425\u9500\u9875\u9762\u5730\u5740')),
                ('course_color', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u914d\u8272')),
                ('discount', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='\u6298\u6263')),
                ('click_count', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('index', models.IntegerField(default=999, verbose_name='\u804c\u4e1a\u8bfe\u7a0b\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO\u6807\u9898')),
                ('seo_keyword', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO\u5173\u952e\u8bcd')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO\u63cf\u8ff0')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'career_course',
                'verbose_name': '\u804c\u4e1a\u8bfe\u7a0b',
                'verbose_name_plural': '\u804c\u4e1a\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding', models.CharField(max_length=30, unique=True, verbose_name='\u73ed\u7ea7\u7f16\u53f7')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('date_open', models.DateTimeField(verbose_name='\u5f00\u8bfe\u65e5\u671f')),
                ('student_limit', models.IntegerField(default=25, verbose_name='\u5b66\u751f\u4e0a\u9650')),
                ('current_student_count', models.IntegerField(default=0, verbose_name='\u5f53\u524d\u62a5\u540d\u6570')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
                ('status', models.SmallIntegerField(choices=[(1, '\u8fdb\u884c\u4e2d'), (2, '\u5df2\u7ed3\u675f')], default=1, verbose_name='\u73ed\u7ea7\u72b6\u6001')),
                ('qq', models.CharField(max_length=13, verbose_name='\u73ed\u7ea7QQ\u7fa4')),
                ('career_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.CareerCourse', verbose_name='\u804c\u4e1a\u8bfe\u7a0b')),
            ],
            options={
                'db_table': 'class',
                'verbose_name': '\u73ed\u7ea7',
                'verbose_name_plural': '\u73ed\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='ClassStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_point', models.IntegerField(default=0, verbose_name='\u5b66\u751f\u5728\u8be5\u73ed\u7ea7\u4e0b\u7684\u5b66\u529b')),
                ('pause_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6682\u505c\u539f\u56e0')),
                ('pause_datetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u6682\u505c\u65f6\u95f4')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Class', verbose_name='\u73ed\u7ea7')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5b66\u751f')),
            ],
            options={
                'ordering': ['-study_point'],
                'db_table': 'class_students',
                'verbose_name': '\u73ed\u7ea7\u5b66\u751f',
                'verbose_name_plural': '\u73ed\u7ea7\u5b66\u751f',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('image', models.ImageField(upload_to=b'course/%Y/%m', verbose_name='\u8bfe\u7a0b\u5c01\u9762')),
                ('description', models.TextField(verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('need_days', models.IntegerField(default=7, verbose_name='\u65e0\u57fa\u7840\u5b66\u751f\u5b8c\u6210\u5929\u6570')),
                ('need_days_base', models.IntegerField(default=5, verbose_name='\u6709\u57fa\u7840\u5b66\u751f\u5b8c\u6210\u5929\u6570')),
                ('student_count', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570')),
                ('click_count', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('is_novice', models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u65b0\u624b\u8bfe\u7a0b')),
                ('is_click', models.BooleanField(default=False, verbose_name='\u662f\u5426\u70b9\u51fb\u80fd\u8fdb\u5165\u8bfe\u7a0b')),
                ('index', models.IntegerField(default=999, verbose_name='\u8bfe\u7a0b\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
                ('is_homeshow', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5728\u9996\u9875\u663e\u793a')),
                ('is_required', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5fc5\u4fee')),
            ],
            options={
                'db_table': 'course',
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u8d44\u6e90\u540d\u79f0')),
                ('download_url', models.FileField(upload_to=b'course/%Y/%m', verbose_name='\u4e0b\u8f7d\u5730\u5740')),
                ('download_count', models.IntegerField(default=0, verbose_name='\u4e0b\u8f7d\u6b21\u6570')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'db_table': 'course_resource',
                'verbose_name': '\u8bfe\u7a0b\u8d44\u6e90',
                'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8ba8\u8bba\u5185\u5bb9')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='\u7236\u8ba8\u8bbaID')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'db_table': 'discuss',
                'verbose_name': '\u8bfe\u7a0b\u8ba8\u8bba',
                'verbose_name_plural': '\u8bfe\u7a0b\u8ba8\u8bba',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='\u9a8c\u8bc1\u7801')),
                ('email', models.CharField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('type', models.SmallIntegerField(choices=[(0, '\u6ce8\u518c'), (1, '\u5fd8\u8bb0\u5bc6\u7801')], default=0, verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b')),
                ('ip', models.CharField(max_length=20, verbose_name='\u8bf7\u6c42\u6765\u6e90IP')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'email_verify_record',
                'verbose_name': '\u90ae\u7bb1\u9a8c\u8bc1\u8bb0\u5f55',
                'verbose_name_plural': '\u90ae\u7bb1\u9a8c\u8bc1\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5173\u952e\u8bcd')),
            ],
            options={
                'db_table': 'keywords',
                'verbose_name': '\u5173\u952e\u8bcd',
                'verbose_name_plural': '\u5173\u952e\u8bcd',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u7ae0\u8282\u540d\u79f0')),
                ('video_url', models.CharField(max_length=200, verbose_name='\u89c6\u9891\u8d44\u6e90URL')),
                ('video_length', models.IntegerField(verbose_name='\u89c6\u9891\u957f\u5ea6\uff08\u79d2\uff09')),
                ('play_count', models.IntegerField(default=0, verbose_name='\u64ad\u653e\u6b21\u6570')),
                ('share_count', models.IntegerField(default=0, verbose_name='\u5206\u4eab\u6b21\u6570')),
                ('index', models.IntegerField(default=999, verbose_name='\u7ae0\u8282\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
                ('is_popup', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5f39\u51fa\u63d0\u793a\u6846\uff08\u652f\u4ed8\u3001\u767b\u5f55\uff09')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO\u6807\u9898')),
                ('seo_keyword', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO\u5173\u952e\u8bcd')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO\u63cf\u8ff0')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'ordering': ['index', 'id'],
                'db_table': 'lesson',
                'verbose_name': '\u89c6\u9891\u7ae0\u8282',
                'verbose_name_plural': '\u89c6\u9891\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u7ae0\u8282\u8d44\u6e90\u540d\u79f0')),
                ('download_url', models.FileField(upload_to=b'lesson/%Y/%m', verbose_name='\u4e0b\u8f7d\u5730\u5740')),
                ('download_count', models.IntegerField(default=0, verbose_name='\u4e0b\u8f7d\u6b21\u6570')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Lesson', verbose_name='\u7ae0\u8282')),
            ],
            options={
                'db_table': 'lesson_resource',
                'verbose_name': '\u7ae0\u8282\u8d44\u6e90',
                'verbose_name_plural': '\u7ae0\u8282\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('description', models.CharField(max_length=200, verbose_name='\u53cb\u60c5\u94fe\u63a5\u63cf\u8ff0')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=b'links/%Y/%m', verbose_name='\u56fe\u7247\u8def\u5f84')),
                ('callback_url', models.URLField(verbose_name='\u56de\u8c03url')),
                ('is_pic', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u56fe\u7247')),
            ],
            options={
                'db_table': 'links',
                'verbose_name': '\u53cb\u60c5\u94fe\u63a5',
                'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5',
            },
        ),
        migrations.CreateModel(
            name='MyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10, verbose_name='\u8bfe\u7a0bID')),
                ('course_type', models.SmallIntegerField(choices=[(1, '\u8bfe\u7a0b'), (2, '\u804c\u4e1a\u8bfe\u7a0b')], verbose_name='\u8bfe\u7a0b\u7c7b\u578b')),
                ('index', models.IntegerField(default=999, verbose_name='\u8bfe\u7a0b\u663e\u793a\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_user', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'my_course',
                'verbose_name': '\u6211\u7684\u8bfe\u7a0b',
                'verbose_name_plural': '\u6211\u7684\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='MyFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_favorite', models.DateTimeField(auto_now_add=True, verbose_name='\u6536\u85cf\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Course', verbose_name='\u8bfe\u7a0b')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mf_user', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'my_favorite',
                'verbose_name': '\u6211\u7684\u6536\u85cf',
                'verbose_name_plural': '\u6211\u7684\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='MyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userA', models.IntegerField(verbose_name='\u7528\u6237A')),
                ('userB', models.IntegerField(verbose_name='\u7528\u6237B')),
                ('action_type', models.CharField(choices=[(b'1', '\u7cfb\u7edf\u6d88\u606f'), (b'2', '\u8bfe\u7a0b\u8ba8\u8bba\u56de\u590d'), (b'3', '\u8bba\u575b\u8ba8\u8bba\u56de\u590d')], max_length=1, verbose_name='\u7c7b\u578b')),
                ('action_id', models.IntegerField(blank=True, null=True, verbose_name='\u52a8\u4f5cid')),
                ('action_content', models.TextField(blank=True, null=True, verbose_name='\u6d88\u606f\u5185\u5bb9')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
                ('is_new', models.BooleanField(default=True, verbose_name='\u662f\u5426\u4e3a\u6700\u65b0')),
            ],
            options={
                'db_table': 'my_message',
                'verbose_name': '\u6211\u7684\u6d88\u606f',
                'verbose_name_plural': '\u6211\u7684\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='RecommendedReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[(b'AV', b'\xe5\xae\x98\xe6\x96\xb9\xe6\xb4\xbb\xe5\x8a\xa8'), (b'NW', b'\xe5\xbc\x80\xe5\x8f\x91\xe8\x80\x85\xe8\xb5\x84\xe8\xae\xaf'), (b'DC', b'\xe6\x8a\x80\xe6\x9c\xaf\xe4\xba\xa4\xe6\xb5\x81')], default=b'AV', max_length=2, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('title', models.CharField(max_length=200, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u6587\u7ae0\u94fe\u63a5')),
            ],
            options={
                'db_table': 'recommended_reading',
                'verbose_name': '\u9996\u9875\u63a8\u8350\u6587\u7ae0',
                'verbose_name_plural': '\u9996\u9875\u63a8\u8350\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='RecommendKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u63a8\u8350\u641c\u7d22\u5173\u952e\u8bcd')),
            ],
            options={
                'db_table': 'recommend_keywords',
                'verbose_name': '\u63a8\u8350\u641c\u7d22\u5173\u952e\u8bcd',
                'verbose_name_plural': '\u63a8\u8350\u641c\u7d22\u5173\u952e\u8bcd',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u9636\u6bb5\u540d\u79f0')),
                ('description', models.TextField(verbose_name='\u9636\u6bb5\u63cf\u8ff0')),
                ('price', models.IntegerField(verbose_name='\u9636\u6bb5\u4ef7\u683c')),
                ('index', models.IntegerField(default=999, verbose_name='\u9636\u6bb5\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
                ('is_try', models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u8bd5\u5b66\u9636\u6bb5')),
                ('career_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.CareerCourse', verbose_name='\u804c\u4e1a\u8bfe\u7a0b')),
            ],
            options={
                'ordering': ['index', 'id'],
                'db_table': 'stage',
                'verbose_name': '\u8bfe\u7a0b\u9636\u6bb5',
                'verbose_name_plural': '\u8bfe\u7a0b\u9636\u6bb5',
            },
        ),
        migrations.CreateModel(
            name='UserLearningLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_learning', models.DateTimeField(auto_now=True, verbose_name='\u6700\u8fd1\u5b66\u4e60\u65f6\u95f4')),
                ('is_complete', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5b8c\u6210\u89c2\u770b')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Lesson', verbose_name='\u7ae0\u8282')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'user_learning_lesson',
                'verbose_name': '\u6211\u7684\u7ae0\u8282',
                'verbose_name_plural': '\u6211\u7684\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_price', models.IntegerField(verbose_name='\u91d1\u989d')),
                ('order_no', models.CharField(max_length=100, unique=True, verbose_name='\u8ba2\u5355\u53f7')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='\u4ea4\u6613\u53f7')),
                ('pay_type', models.SmallIntegerField(choices=[(0, '\u5168\u6b3e'), (1, '\u8bd5\u5b66\u9996\u4ed8\u6b3e'), (2, '\u5c3e\u6b3e'), (3, '\u9636\u6bb5\u6b3e')], default=0, verbose_name='\u652f\u4ed8\u7c7b\u578b')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0b\u5355\u65f6\u95f4')),
                ('date_pay', models.DateTimeField(blank=True, null=True, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('pay_way', models.SmallIntegerField(choices=[(1, '\u7f51\u9875\u652f\u4ed8\u5b9d'), (2, '\u79fb\u52a8\u652f\u4ed8\u5b9d')], verbose_name='\u652f\u4ed8\u65b9\u5f0f')),
                ('pay_status', models.SmallIntegerField(blank=True, choices=[(0, '\u672a\u652f\u4ed8'), (1, '\u652f\u4ed8\u6210\u529f'), (2, '\u652f\u4ed8\u5931\u8d25')], default=0, null=True, verbose_name='\u652f\u4ed8\u72b6\u6001')),
                ('pay_careercourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.CareerCourse', verbose_name='\u652f\u4ed8\u8ba2\u5355\u5bf9\u5e94\u804c\u4e1a\u8bfe\u7a0b')),
                ('pay_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Class', verbose_name='\u652f\u4ed8\u8ba2\u5355\u5bf9\u5e94\u73ed\u7ea7\u53f7')),
                ('pay_stage', models.ManyToManyField(to='common.Stage', verbose_name='\u652f\u4ed8\u8ba2\u5355\u5bf9\u5e94\u9636\u6bb5')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'user_purchase',
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='UserUnlockStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_unlock', models.DateTimeField(auto_now_add=True, verbose_name='\u89e3\u9501\u65f6\u95f4')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Stage', verbose_name='\u89e3\u9501\u7684\u9636\u6bb5')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'user_unlock_stage',
                'verbose_name': '\u6211\u7684\u89e3\u9501\u9636\u6bb5',
                'verbose_name_plural': '\u6211\u7684\u89e3\u9501\u9636\u6bb5',
            },
        ),
        migrations.AddField(
            model_name='discuss',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Lesson', verbose_name='\u7ae0\u8282'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='user_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Class', verbose_name='\u73ed\u7ea7'),
        ),
        migrations.AddField(
            model_name='course',
            name='search_keywords',
            field=models.ManyToManyField(to='common.Keywords', verbose_name='\u5c0f\u8bfe\u7a0b\u641c\u7d22\u5173\u952e\u8bcd'),
        ),
        migrations.AddField(
            model_name='course',
            name='stages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Stage', verbose_name='\u9636\u6bb5'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8001\u5e08'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='students', through='common.ClassStudents', to=settings.AUTH_USER_MODEL, verbose_name='\u73ed\u7ea7\u5b66\u751f'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='\u73ed\u7ea7\u8001\u5e08'),
        ),
        migrations.AddField(
            model_name='careercourse',
            name='search_keywords',
            field=models.ManyToManyField(to='common.Keywords', verbose_name='\u641c\u7d22\u5173\u952e\u8bcd'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='myfavorite',
            field=models.ManyToManyField(through='common.MyFavorite', to='common.Course', verbose_name='\u6211\u7684\u6536\u85cf'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mylesson',
            field=models.ManyToManyField(through='common.UserLearningLesson', to='common.Lesson', verbose_name='\u6211\u7684\u5b66\u4e60\u7ae0\u8282'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mystage',
            field=models.ManyToManyField(through='common.UserUnlockStage', to='common.Stage', verbose_name='\u6211\u7684\u89e3\u9501\u9636\u6bb5'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='userunlockstage',
            unique_together=set([('user', 'stage')]),
        ),
        migrations.AlterUniqueTogether(
            name='userlearninglesson',
            unique_together=set([('user', 'lesson')]),
        ),
        migrations.AlterUniqueTogether(
            name='myfavorite',
            unique_together=set([('user', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='classstudents',
            unique_together=set([('user', 'student_class')]),
        ),
    ]
