# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-06 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=8, verbose_name='\u9a8c\u8bc1\u7801'),
        ),
    ]
